### ISSUE TITLE
FeedParser issue 

### ISSUE THREAD

**Issue by JoshuaEpl** [nmdias/FeedParser#1]
In the Core folder. 
The FeedParser.swift file. 

Error: All stored properties of a class instance must be initialized before returning nil form an initializer    

I am using xcode version 7.2 if that helps. 

 public init?(URL: NSURL) {

```
    guard let parser = Parser(contentsOfURL: URL) else {
```

 //This line gives me a error. ------->  return nil
        }

```
    self.parser = parser

}
```

**Comment by nmdias** [comment]
It does help, it is a known issue of Xcode 7.2, where all properties of an instance must be initialized before nil is returned. However, this does not make sense if, for whatever reason, you need to return nil in a failable initializer before doing so. 

This was fixed in Xcode 7.3
