### ISSUE TITLE
FeedParser class and namespace

### ISSUE THREAD

**Issue by JARMourato** [nmdias/FeedParser#2]
Hi, I'm facing an issue with your library. I have already an implementation of Result Enum in my project. Since your module FeedParser has a class named exactly the same I cannot specify in my code your version of Result as FeedParser.Result since XCode always assumes the class FeedParser type.

**Comment by nmdias** [comment]
Nice catch @JARMourato I'll release a fix for this. Thanks :)

**Comment by JARMourato** [comment]
Don't know what your approach will be..but either changing the module name in the podspec or the class name should get the job done.
Many thanks @nmdias happy to help ;)

**Comment by nmdias** [comment]
Agree. I'll probably rename the class to `Parser` and be done with it. Renaming the module as too many ramifications, and would have to actually rename the entire framework, submit a new pod under a new name and thus reducing the change of discoverability....and so on.

**Comment by JARMourato** [comment]
You can specify in the podspec a variable named modulename, and nothing changes other than the import FeedParser changing to (e.g. FeedParserFramework). Just letting you know, either way is fine by me :)

**Comment by nmdias** [comment]
The framework has now been renamed [FeedKit](https://github.com/nmdias/FeedKit) and moved to a [new repository](https://github.com/nmdias/FeedKit). Naming collisions between the module import and the `FeedParser` class name should no longer pose any issues.

Thank you again for reporting this issue @JARMourato
